"""init schema

Revision ID: ecfe127bd397
Revises: 
Create Date: 2026-06-04 01:32:42.114169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecfe127bd397'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backgrounds',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('legacy_id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('final_prompt', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backgrounds'))
    )
    op.create_index(op.f('ix_backgrounds_legacy_id'), 'backgrounds', ['legacy_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('legacy_id', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index(op.f('ix_users_legacy_id'), 'users', ['legacy_id'], unique=False)
    op.create_table('voices',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('legacy_id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('voice_prompt', sa.Text(), nullable=True),
    sa.Column('voice_type', sa.Text(), server_default='character', nullable=False),
    sa.Column('is_preset', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('speaker_label', sa.Text(), nullable=True),
    sa.Column('character_id', sa.Text(), nullable=True),
    sa.Column('reference_audio_url', sa.Text(), nullable=True),
    sa.Column('reference_text', sa.Text(), nullable=True),
    sa.Column('sample_audio_url', sa.Text(), nullable=True),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('pending','processing','ready','failed')", name=op.f('ck_voices_voice_status_valid')),
    sa.CheckConstraint("voice_type in ('narrator','character')", name=op.f('ck_voices_voice_type_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_voices'))
    )
    op.create_index(op.f('ix_voices_is_preset'), 'voices', ['is_preset'], unique=False)
    op.create_index(op.f('ix_voices_legacy_id'), 'voices', ['legacy_id'], unique=False)
    op.create_index(op.f('ix_voices_status'), 'voices', ['status'], unique=False)
    op.create_table('characters',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('legacy_id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('appearance_prompt', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('ai_image_path', sa.Text(), nullable=True),
    sa.Column('voice_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['voice_id'], ['voices.id'], name=op.f('fk_characters_voice_id_voices'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_characters'))
    )
    op.create_index(op.f('ix_characters_legacy_id'), 'characters', ['legacy_id'], unique=False)
    op.create_index(op.f('ix_characters_name'), 'characters', ['name'], unique=False)
    op.create_index(op.f('ix_characters_voice_id'), 'characters', ['voice_id'], unique=False)
    op.create_table('stories',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('legacy_id', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('narrator_voice_id', sa.Text(), nullable=True),
    sa.Column('voice_locks', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['narrator_voice_id'], ['voices.id'], name=op.f('fk_stories_narrator_voice_id_voices'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stories'))
    )
    op.create_index(op.f('ix_stories_legacy_id'), 'stories', ['legacy_id'], unique=False)
    op.create_table('character_poses',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('legacy_id', sa.Text(), nullable=True),
    sa.Column('character_id', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_character_poses_character_id_characters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_character_poses'))
    )
    op.create_index(op.f('ix_character_poses_character_id'), 'character_poses', ['character_id'], unique=False)
    op.create_index(op.f('ix_character_poses_legacy_id'), 'character_poses', ['legacy_id'], unique=False)
    op.create_table('render_results',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('legacy_id', sa.Text(), nullable=True),
    sa.Column('story_id', sa.Text(), nullable=False),
    sa.Column('video_url', sa.Text(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('status', sa.Text(), server_default='completed', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('generating','completed','failed')", name=op.f('ck_render_results_render_status_valid')),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('fk_render_results_story_id_stories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_render_results'))
    )
    op.create_index(op.f('ix_render_results_legacy_id'), 'render_results', ['legacy_id'], unique=False)
    op.create_index(op.f('ix_render_results_story_id'), 'render_results', ['story_id'], unique=False)
    op.create_table('scenes',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('legacy_id', sa.Text(), nullable=True),
    sa.Column('story_id', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Float(), server_default=sa.text('3.0'), nullable=False),
    sa.Column('background_id', sa.Text(), nullable=True),
    sa.Column('scene_text_color', sa.Text(), nullable=True),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('cue_timings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('subtitle_settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration >= 1.0 and duration <= 30.0', name=op.f('ck_scenes_scene_duration_range')),
    sa.ForeignKeyConstraint(['background_id'], ['backgrounds.id'], name=op.f('fk_scenes_background_id_backgrounds'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('fk_scenes_story_id_stories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenes')),
    sa.UniqueConstraint('story_id', 'order_index', name='uq_scene_story_order')
    )
    op.create_index(op.f('ix_scenes_legacy_id'), 'scenes', ['legacy_id'], unique=False)
    op.create_index(op.f('ix_scenes_story_id'), 'scenes', ['story_id'], unique=False)
    op.create_table('scene_characters',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('scene_id', sa.Text(), nullable=False),
    sa.Column('character_id', sa.Text(), nullable=False),
    sa.Column('pose_id', sa.Text(), nullable=True),
    sa.Column('layout', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_scene_characters_character_id_characters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pose_id'], ['character_poses.id'], name=op.f('fk_scene_characters_pose_id_character_poses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], name=op.f('fk_scene_characters_scene_id_scenes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scene_characters')),
    sa.UniqueConstraint('scene_id', 'character_id', name='uq_scene_character')
    )
    op.create_index(op.f('ix_scene_characters_character_id'), 'scene_characters', ['character_id'], unique=False)
    op.create_index(op.f('ix_scene_characters_scene_id'), 'scene_characters', ['scene_id'], unique=False)
    op.create_table('tts_audios',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('legacy_id', sa.Text(), nullable=True),
    sa.Column('scene_id', sa.Text(), nullable=False),
    sa.Column('story_id', sa.Text(), nullable=False),
    sa.Column('item_index', sa.Integer(), nullable=False),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('speaker', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('emotion', sa.Text(), nullable=True),
    sa.Column('emotion_label', sa.Text(), nullable=True),
    sa.Column('voice_id', sa.Text(), nullable=True),
    sa.Column('audio_url', sa.Text(), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], name=op.f('fk_tts_audios_scene_id_scenes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('fk_tts_audios_story_id_stories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voice_id'], ['voices.id'], name=op.f('fk_tts_audios_voice_id_voices'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tts_audios')),
    sa.UniqueConstraint('scene_id', 'item_index', name='uq_ttsaudio_scene_item')
    )
    op.create_index(op.f('ix_tts_audios_legacy_id'), 'tts_audios', ['legacy_id'], unique=False)
    op.create_index(op.f('ix_tts_audios_scene_id'), 'tts_audios', ['scene_id'], unique=False)
    op.create_index(op.f('ix_tts_audios_story_id'), 'tts_audios', ['story_id'], unique=False)
    op.create_index(op.f('ix_tts_audios_voice_id'), 'tts_audios', ['voice_id'], unique=False)
    # ### end Alembic commands ###

    # updated_at 자동 갱신 트리거 (앱에서 빠뜨려도 DB가 갱신)
    op.execute(
        """
        CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    for _t in ("voices", "backgrounds", "characters", "stories", "scenes", "users"):
        op.execute(
            f"CREATE TRIGGER trg_{_t}_updated_at BEFORE UPDATE ON {_t} "
            f"FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
        )


def downgrade() -> None:
    """Downgrade schema."""
    # updated_at 트리거/함수 제거
    for _t in ("voices", "backgrounds", "characters", "stories", "scenes", "users"):
        op.execute(f"DROP TRIGGER IF EXISTS trg_{_t}_updated_at ON {_t};")
    op.execute("DROP FUNCTION IF EXISTS set_updated_at();")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tts_audios_voice_id'), table_name='tts_audios')
    op.drop_index(op.f('ix_tts_audios_story_id'), table_name='tts_audios')
    op.drop_index(op.f('ix_tts_audios_scene_id'), table_name='tts_audios')
    op.drop_index(op.f('ix_tts_audios_legacy_id'), table_name='tts_audios')
    op.drop_table('tts_audios')
    op.drop_index(op.f('ix_scene_characters_scene_id'), table_name='scene_characters')
    op.drop_index(op.f('ix_scene_characters_character_id'), table_name='scene_characters')
    op.drop_table('scene_characters')
    op.drop_index(op.f('ix_scenes_story_id'), table_name='scenes')
    op.drop_index(op.f('ix_scenes_legacy_id'), table_name='scenes')
    op.drop_table('scenes')
    op.drop_index(op.f('ix_render_results_story_id'), table_name='render_results')
    op.drop_index(op.f('ix_render_results_legacy_id'), table_name='render_results')
    op.drop_table('render_results')
    op.drop_index(op.f('ix_character_poses_legacy_id'), table_name='character_poses')
    op.drop_index(op.f('ix_character_poses_character_id'), table_name='character_poses')
    op.drop_table('character_poses')
    op.drop_index(op.f('ix_stories_legacy_id'), table_name='stories')
    op.drop_table('stories')
    op.drop_index(op.f('ix_characters_voice_id'), table_name='characters')
    op.drop_index(op.f('ix_characters_name'), table_name='characters')
    op.drop_index(op.f('ix_characters_legacy_id'), table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_voices_status'), table_name='voices')
    op.drop_index(op.f('ix_voices_legacy_id'), table_name='voices')
    op.drop_index(op.f('ix_voices_is_preset'), table_name='voices')
    op.drop_table('voices')
    op.drop_index(op.f('ix_users_legacy_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_backgrounds_legacy_id'), table_name='backgrounds')
    op.drop_table('backgrounds')
    # ### end Alembic commands ###
